# Generated by Django 3.1 on 2020-08-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixappt',
            name='fix_clinic',
            field=models.ForeignKey(default='clin', on_delete=django.db.models.deletion.CASCADE, related_name='selected_clinic', to='account.clinics'),
        ),
    ]
